### ISSUE TITLE
Yunzai py-plugin 用户常见问题

### ISSUE THREAD

**Issue by monsterxcn** [monsterxcn/nonebot-plugin-gspanel#17]
Yunzai 用户安装 [@realhuhu/py-plugin](https://github.com/realhuhu/py-plugin) 插件后可以兼容运行此插件！安装步骤如下：

1. 仔细阅读 [README.md - @realhuhu/py-plugin](https://github.com/realhuhu/py-plugin#21-%E5%AE%89%E8%A3%85) 配置 Yunzai Bot 的 Python 运行环境
2. 向 Yunzai Bot 发送 QQ 消息 `#py下载插件nonebot-plugin-gspanel` 安装此插件
3. [建议] 将 [使用须知](https://github.com/monsterxcn/nonebot-plugin-gspanel#%E4%BD%BF%E7%94%A8%E9%A1%BB%E7%9F%A5) 第 4 条中交待的所有环境变量写入 py-plugin 的配置文件 config.yaml 中，**注意格式**
4. [建议] 将环境变量 `gspanel_alias` 定义为 `面板` 以外的触发词，避免此插件与 Yunzai 及其插件的相关功能同时触发

py-plugin 的配置文件 config.yaml 中 **务必手动添加** 此插件的一些配置，下面的配置仅供参考，不要盲目复制。

```yaml
log_level: INFO
nickname:
  - 云崽
  - yunzai
superusers:
  - 123456
  - 654321
need_at: no #是否需要@机器人或加上机器人名字，默认no
plugins:
  - nonebot-plugin-petpet
  - nonebot-plugin-memes
  # 加载哪些插件就继续往下加
  - nonebot_plugin_gspanel  # 确保这里有且仅有一个
host: 127.0.0.1
port: 50052
independent: false #py服务器与云崽本体分开启动
#encoding: gbk #如果输出乱码，可以开启这项试试看，主要是windows平台

# nonebot-plugin-gspanel 配置项
gspanel_alias:  # 注意下面 - 前的缩进，空格不要随心所欲
  - 想要的面板触发词
  - 支持多个面板触发词
gspanel_scale: 1.0  # 值越大返回图片分辨率越高
resources_mirror: https://enka.network/ui/
# 下面这个填自己的 py-plugin/data 完整路径，不要照抄！
# Windows 的路径要将反斜杠 \ 替换为 /
resources_dir: /path/to/py-plugin/data
```

 

有任何 py-plugin 下 **安装使用此插件的问题**（py-plugin 的问题请去 [这里](https://github.com/realhuhu/py-plugin/issues) 提问！在此处提问可能被折叠），都可以在下方回帖提问，注意带上具体报错 **触发条件** 及 **日志**（通常截取最后一段即可）等信息。
